window.JOURNAL_POSTS=[
{slug:"what-is-aging",category:"health",date:"2026-10-08",title:"노화란 무엇인가: 건강수명을 바라보는 관점",excerpt:"노화의 정의, 건강수명, 생활 습관의 역할을 정리한 아카이브의 첫 글.",tags:["노화","건강수명","항노화"],html:"<p>노화는 시간이 흐르며 생물학적 기능과 회복 능력이 변화하는 복합적인 과정입니다. 수명을 늘리는 문제와 건강하게 지내는 기간을 늘리는 문제는 구분해 생각할 필요가 있습니다.</p><h2>이 매거진의 원칙</h2><p>연구에서 확인된 결과, 아직 검증되지 않은 가설, 개인적인 경험을 명확히 구분합니다.</p><p><strong>편집 메모:</strong> 사이트 구성을 위한 예시 원고입니다. 기존 Tistory 원문은 아직 이전하지 않았습니다.</p>"},
{slug:"running-journal",category:"running",date:"2026-10-08",title:"러닝 저널: 기록보다 중요한 지속성",excerpt:"훈련량과 강도, 회복을 함께 기록하는 러닝 아카이브의 시작.",tags:["러닝","훈련","회복"],html:"<p>달리기 기록을 개선하는 과정에서 훈련 자체만큼 중요한 것은 회복과 부상 관리입니다. 주간 거리, 강도, 수면, 컨디션을 함께 기록하면 변화의 원인을 더 잘 이해할 수 있습니다.</p><h2>앞으로 기록할 것</h2><p>훈련 일지, 레이스 후기, 러닝화 사용기, 부상 예방에 대한 근거 기반 자료를 축적합니다.</p><p><strong>편집 메모:</strong> 실제 러닝 기록을 자동으로 불러오지는 않습니다.</p>"},
{slug:"research-notes",category:"research",date:"2026-10-08",title:"논문을 읽을 때 확인할 다섯 가지",excerpt:"연구 설계와 근거 수준을 구분하는 개인 리서치 노트.",tags:["논문","연구","근거"],html:"<p>흥미로운 연구 결과를 접하면 연구 대상, 표본 규모, 관찰 기간, 대조군 여부, 실제 효과 크기를 함께 확인합니다.</p><h2>개인적 적용은 별개의 문제</h2><p>동물 실험이나 세포 실험의 결과가 곧바로 사람에게서 동일한 효과를 뜻하지는 않습니다.</p><p><strong>편집 메모:</strong> 향후 출처 링크와 연구 요약을 추가할 수 있습니다.</p>"}

,{slug:"bike-types-guide-2023",category:"running",date:"2023-07-29",title:"자전거의 종류와 선택 — 라이딩 아카이브",excerpt:"로드·산악·생활·화물 자전거의 특징과 용도를 원문을 바탕으로 재분류했습니다.",tags:["자전거","라이딩","장비"],html:"<p><strong>원문:</strong> My EPIC2 · Ziusudra · 2023년 7월 29일</p><p>자전거는 사용 목적과 노면에 따라 적합한 유형이 달라집니다. 기존에 작성한 글의 분류를 매거진형 목차로 정리했습니다.</p><h2>01. 포장도로와 장거리</h2><p>로드, 타임 트라이얼, 픽시, 미니 스프린터, 투어링, 랜도너 등 주행 목적에 따른 선택지를 다룹니다.</p><h2>02. 산악과 비포장도로</h2><p>크로스컨트리, 트레일, 올마운틴, 다운힐, 팻바이크, 그래블 바이크 등을 구분합니다.</p><h2>03. 일상생활과 운반</h2><p>미니벨로, 접이식, 하이브리드, 크루저, 전기자전거, 카고 바이크 등 일상적 활용을 중심으로 살펴봅니다.</p><p><strong>원문 전체 및 사진:</strong> <a href='https://myepic2.tistory.com/9' target='_blank' rel='noopener noreferrer'>My EPIC2에서 읽기 ↗</a></p><p><em>편집 상태: 원문 기반 목차·소개글 이전 완료. 본문과 이미지는 아직 전체 이전 전입니다.</em></p>"}
,
{"slug":"nmn-evidence-guide","category":"health","date":"2023-07-21","title":"NMN과 NAD⁺: 세포 대사에서 건강수명까지","excerpt":"2023년 Tistory 원문을 바탕으로 NMN의 작용 가설과 인체 근거의 간극을 짚습니다.","tags":["NMN","NAD+","Longevity Molecules"],"html":"<p><strong>아카이브 원문:</strong> <a href=\"https://myepic2.tistory.com/6\" target=\"_blank\" rel=\"noopener noreferrer\">myepic2 원문 보기 ↗</a></p><h2>30초 핵심 요약</h2><p>원문은 NMN과 NAD⁺, 시르투인, DNA 수선의 관계를 설명하고 관련 연구를 인용합니다. 그러나 세포 기전이나 생체지표의 변화가 사람의 수명 연장을 입증하는 것은 아닙니다.</p><h2>핵심 질문</h2><p>NMN이 실제로 건강수명을 늘리는가?</p><h2>원문에 수록된 참고 논문</h2><p>기존 글에서 인용한 논문 링크는 <a href=\"https://github.com/Jacobkang80/longevity-journal/blob/main/data/original-references.json\" target=\"_blank\" rel=\"noopener noreferrer\">원문 근거 아카이브</a>에 보존했습니다. 발표 연도순 타임라인과 연구 수준 평가는 논문별 원문 검증 후 추가합니다.</p><h2>편집 기록</h2><p>원문 작성일을 유지한 1차 편집 소개글입니다. 원문 본문·이미지 전체 이전 및 최신 논문 검토는 진행 중이며, 위 설명은 의료적 효능을 확정하는 주장이 아닙니다.</p>"},
{"slug":"fisetin-evidence-guide","category":"health","date":"2023-07-21","title":"Fisetin: 노화세포 제거 가능성과 남은 질문","excerpt":"세놀리틱 연구와 사람에게 적용할 때 필요한 근거를 구분합니다.","tags":["Fisetin","세놀리틱","Longevity Molecules"],"html":"<p><strong>아카이브 원문:</strong> <a href=\"https://myepic2.tistory.com/5\" target=\"_blank\" rel=\"noopener noreferrer\">myepic2 원문 보기 ↗</a></p><h2>30초 핵심 요약</h2><p>원문은 Fisetin의 폴리페놀 특성과 노화세포 제거에 관한 동물·기전 연구를 소개합니다. 동물에서 관찰된 결과나 유명 연구자의 복용 사례만으로 사람의 항노화 효과와 적정 용량을 확정할 수 없습니다.</p><h2>핵심 질문</h2><p>사람 대상 임상시험에서 의미 있는 건강 효과가 재현됐는가?</p><h2>원문에 수록된 참고 논문</h2><p>기존 글에서 인용한 논문 링크는 <a href=\"https://github.com/Jacobkang80/longevity-journal/blob/main/data/original-references.json\" target=\"_blank\" rel=\"noopener noreferrer\">원문 근거 아카이브</a>에 보존했습니다. 발표 연도순 타임라인과 연구 수준 평가는 논문별 원문 검증 후 추가합니다.</p><h2>편집 기록</h2><p>원문 작성일을 유지한 1차 편집 소개글입니다. 원문 본문·이미지 전체 이전 및 최신 논문 검토는 진행 중이며, 위 설명은 의료적 효능을 확정하는 주장이 아닙니다.</p>"},
{"slug":"ca-akg-evidence-guide","category":"health","date":"2024-02-26","title":"CA-AKG: 에너지 대사와 노화 연구의 접점","excerpt":"알파케토글루타레이트의 대사적 역할과 항노화 주장의 근거를 분리합니다.","tags":["CA-AKG","대사","Longevity Molecules"],"html":"<p><strong>아카이브 원문:</strong> <a href=\"https://myepic2.tistory.com/42\" target=\"_blank\" rel=\"noopener noreferrer\">myepic2 원문 보기 ↗</a></p><h2>30초 핵심 요약</h2><p>원문은 α-KG의 TCA 회로·후성유전 조절과 관련된 연구, 특히 동물 연구를 소개합니다. α-KG와 칼슘염 보충제 CA-AKG를 동일한 임상 효과로 취급해서는 안 됩니다.</p><h2>핵심 질문</h2><p>보충제로 복용한 CA-AKG의 사람 대상 임상 결과가 있는가?</p><h2>원문에 수록된 참고 논문</h2><p>기존 글에서 인용한 논문 링크는 <a href=\"https://github.com/Jacobkang80/longevity-journal/blob/main/data/original-references.json\" target=\"_blank\" rel=\"noopener noreferrer\">원문 근거 아카이브</a>에 보존했습니다. 발표 연도순 타임라인과 연구 수준 평가는 논문별 원문 검증 후 추가합니다.</p><h2>편집 기록</h2><p>원문 작성일을 유지한 1차 편집 소개글입니다. 원문 본문·이미지 전체 이전 및 최신 논문 검토는 진행 중이며, 위 설명은 의료적 효능을 확정하는 주장이 아닙니다.</p>"},
{"slug":"omega3-evidence-guide","category":"health","date":"2023-07-29","title":"오메가3: 심혈관 건강과 인지 기능의 근거 읽기","excerpt":"오메가3의 다양한 건강 주장을 결과 지표별로 나누어 살펴봅니다.","tags":["오메가3","심혈관","Longevity Molecules"],"html":"<p><strong>아카이브 원문:</strong> <a href=\"https://myepic2.tistory.com/13\" target=\"_blank\" rel=\"noopener noreferrer\">myepic2 원문 보기 ↗</a></p><h2>30초 핵심 요약</h2><p>원문은 오메가3와 혈중 지질, 심혈관 및 인지 건강의 관계를 폭넓게 다룹니다. 중성지방 감소, 심혈관 사건 예방, 치매 예방은 서로 다른 평가 항목이며 결과를 혼동해서는 안 됩니다.</p><h2>핵심 질문</h2><p>어떤 대상군에서 어떤 결과가 개선됐는가?</p><h2>원문에 수록된 참고 논문</h2><p>기존 글에서 인용한 논문 링크는 <a href=\"https://github.com/Jacobkang80/longevity-journal/blob/main/data/original-references.json\" target=\"_blank\" rel=\"noopener noreferrer\">원문 근거 아카이브</a>에 보존했습니다. 발표 연도순 타임라인과 연구 수준 평가는 논문별 원문 검증 후 추가합니다.</p><h2>편집 기록</h2><p>원문 작성일을 유지한 1차 편집 소개글입니다. 원문 본문·이미지 전체 이전 및 최신 논문 검토는 진행 중이며, 위 설명은 의료적 효능을 확정하는 주장이 아닙니다.</p>"}
];